package lifeclickapp;

//import eu.lifeclick.backend.RequestManager;
//import eu.lifeclick.backend.RescuerManager;
//import eu.lifeclick.backend.UserManager;
import eu.lifeclick.backend.Request;
import eu.lifeclick.backend.User;
import eu.lifeclick.backend.UserManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import org.apache.derby.jdbc.EmbeddedDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author xcambal
 */
public class LifeClickApp extends javax.swing.JFrame {

    private EmbeddedDataSource dataSource;
    private UserManager userManager;
    private RequestsTableModel reqModel;
    private UserTableModel userModel;
    public static Logger log = LoggerFactory.getLogger(LifeClickApp.class) ;
    //private UserComboModel userCombo;
 /*
    private class GetRequestsSwingWorker extends SwingWorker<Integer,Void> {
        @Override    
        protected Integer doInBackground() throws Exception {
            //TODO: akce provadena na pozadi; vola se na prislusnem miste pomoci metody execute()
            return 0;
        }
        
        @Override    
        protected void done() {
            //...
        }
    }
*/
    /**
     * Creates new form LifeClickApp
     */
    public LifeClickApp() {
        dataSource = new EmbeddedDataSource();
        setupInMemDataSource(); //zde by mohlo byt nastaveni dle properties souboru
        
        initComponents();
        //log : app started
        
        reqModel = (RequestsTableModel) jTableRequests.getModel();
        reqModel.initRequestManager(dataSource);
        
        
        userModel = (UserTableModel) jTableUsers.getModel();
        userModel.initUserManager(dataSource);
        userModel.addUser( new User("franta.mrkvicka@gmail.com", "Franta", "Mrkvička") );
        
        setUserCombo();
    }

    
    private void setUserCombo(){
        List<User> users = (new UserManager(dataSource)).getAll();
        jComboBoxUser.removeAll();
        for (User user : users){
            jComboBoxUser.addItem( new UserComboItem(user) );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTextFieldLatitude = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldlongitude = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxUser = new javax.swing.JComboBox<UserComboItem>();
        jButtonAddRequest = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButtonNewestRequest = new javax.swing.JButton();
        jButtonAllRequests = new javax.swing.JButton();
        jButtonDeleteRequest = new javax.swing.JButton();
        jButtonAuthorOfRequest = new javax.swing.JButton();
        jButtonAllRescuers = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequests = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUSurname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUEmail = new javax.swing.JTextField();
        jButtonAddUser = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonSearchUser = new javax.swing.JButton();
        jTextFieldUNameOrEmail = new javax.swing.JTextField();
        jButtonAllUsers = new javax.swing.JButton();
        jButtonDeleteUser = new javax.swing.JButton();
        jButtonRequestsOfUser = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableUsers = new javax.swing.JTable();
        jButtonEditUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName("tabbedPane"); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "File new request", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N

        jTextFieldLatitude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLatitudeActionPerformed(evt);
            }
        });

        jLabel1.setText("Latitude");

        jLabel5.setText("Longitude");

        jLabel6.setText("User");

        jComboBoxUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserActionPerformed(evt);
            }
        });

        jButtonAddRequest.setText("Add request");
        jButtonAddRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonAddRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLatitude)
                            .addComponent(jTextFieldlongitude)
                            .addComponent(jComboBoxUser, 0, 282, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldlongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonAddRequest)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Find requests"));

        jButtonNewestRequest.setText("Newest requests");
        jButtonNewestRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewestRequestActionPerformed(evt);
            }
        });

        jButtonAllRequests.setText("List all requests");
        jButtonAllRequests.setName(""); // NOI18N
        jButtonAllRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllRequestsActionPerformed(evt);
            }
        });

        jButtonDeleteRequest.setText("Delete selected request");
        jButtonDeleteRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRequestActionPerformed(evt);
            }
        });

        jButtonAuthorOfRequest.setText("Show author of this request");
        jButtonAuthorOfRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthorOfRequestActionPerformed(evt);
            }
        });

        jButtonAllRescuers.setText("Show all rescuers to this request");
        jButtonAllRescuers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllRescuersActionPerformed(evt);
            }
        });

        jTableRequests.setModel(new RequestsTableModel());
        jTableRequests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableRequests);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButtonNewestRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAllRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonDeleteRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAuthorOfRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAllRescuers, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNewestRequest)
                    .addComponent(jButtonAllRequests))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAuthorOfRequest)
                    .addComponent(jButtonAllRescuers))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Requests", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Add new user"));
        jPanel4.setToolTipText("");

        jLabel2.setText("First name");

        jTextFieldUName.setText("first name");

        jLabel3.setText("Last name");

        jTextFieldUSurname.setText("last name");

        jLabel4.setText("Email");

        jTextFieldUEmail.setText("email");

        jButtonAddUser.setText("Add user");
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonAddUser)
                        .addGap(184, 184, 184))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldUEmail)
                            .addComponent(jTextFieldUSurname)
                            .addComponent(jTextFieldUName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAddUser)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("List users"));

        jButtonSearchUser.setText("Search by name or email");
        jButtonSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchUserActionPerformed(evt);
            }
        });

        jTextFieldUNameOrEmail.setToolTipText("Insert email to be searched");

        jButtonAllUsers.setText("List all");
        jButtonAllUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllUsersActionPerformed(evt);
            }
        });

        jButtonDeleteUser.setText("Delete selected user");
        jButtonDeleteUser.setActionCommand("deleteUser");
        jButtonDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteUserActionPerformed(evt);
            }
        });

        jButtonRequestsOfUser.setText("Show all requests of selected user");
        jButtonRequestsOfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestsOfUserActionPerformed(evt);
            }
        });

        jTableUsers.setModel(new UserTableModel());
        jTableUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUsers.setFillsViewportHeight(true);
        jTableUsers.setGridColor(new java.awt.Color(204, 204, 204));
        jTableUsers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTableUsers);

        jScrollPane4.setViewportView(jScrollPane3);

        jButtonEditUser.setText("Edit selected user");
        jButtonEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonAllUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldUNameOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonRequestsOfUser, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 257, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButtonDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchUser)
                    .addComponent(jTextFieldUNameOrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAllUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditUser)
                    .addComponent(jButtonDeleteUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRequestsOfUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Users", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Requests");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRequestsOfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestsOfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRequestsOfUserActionPerformed

    private void jButtonDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteUserActionPerformed
        int row = jTableUsers.getSelectedRow();
        if (row >= 0) {
            //log
            userModel.deleteUser( userModel.getUserAt(row) );
            setUserCombo();
        } else {
            //log : not selected
        }
    }//GEN-LAST:event_jButtonDeleteUserActionPerformed

    private void jButtonAllRescuersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllRescuersActionPerformed
        int row = jTableUsers.getSelectedRow();
        if (row >= 0){
            //log
            jTabbedPane1.setSelectedIndex(1);
            userModel.setUsersByRequest( reqModel.getRequestAt(row) );
        } else {
            // log : no row specified
        }
    }//GEN-LAST:event_jButtonAllRescuersActionPerformed

    private void jButtonAuthorOfRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthorOfRequestActionPerformed
        int row = jTableUsers.getSelectedRow();
        if (row >= 0){
            //log
            jTabbedPane1.setSelectedIndex(1);
            userModel.setUsersById( reqModel.getRequestAt(row).getUser().getId() );
        } else {
            // log : no row specified
        }
    }//GEN-LAST:event_jButtonAuthorOfRequestActionPerformed

    private void jButtonDeleteRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRequestActionPerformed
        int row = jTableUsers.getSelectedRow();
        if (row >= 0){
            //log
            reqModel.removeRequestAt(row);
        } else {
            // log : no row specified
        }
    }//GEN-LAST:event_jButtonDeleteRequestActionPerformed

    private void jComboBoxUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserActionPerformed

    }//GEN-LAST:event_jComboBoxUserActionPerformed

    private void jTextFieldLatitudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLatitudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLatitudeActionPerformed

    private void jButtonAllUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllUsersActionPerformed
        userModel.setAllUsers();
    }//GEN-LAST:event_jButtonAllUsersActionPerformed

    private void jButtonNewestRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewestRequestActionPerformed
        //log
        reqModel.setNewestRequests();
    }//GEN-LAST:event_jButtonNewestRequestActionPerformed

    private void jButtonAllRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllRequestsActionPerformed
        //log
        reqModel.setAllRequests();
    }//GEN-LAST:event_jButtonAllRequestsActionPerformed

    private void jButtonAddRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRequestActionPerformed
        Double latitude = Double.parseDouble(jTextFieldLatitude.getText());
        Double longitude = Double.parseDouble(jTextFieldlongitude.getText());
        User user = ((UserComboItem) jComboBoxUser.getSelectedItem()).getUser() ;
        
        if (user != null){
            //log..
            reqModel.addRequest( new Request(latitude, longitude, user) );
        } else {
            //log : something not specified
        }
    }//GEN-LAST:event_jButtonAddRequestActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        String name = jTextFieldUName.getText();
        String surname = jTextFieldUSurname.getText();
        String email = jTextFieldUEmail.getText();
        
        if (name != null && surname != null && email != null){
            //log..
            userModel.addUser( new User(email, name, surname) );
            
            setUserCombo();
        } else {
            //log : something not specified
        }
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jButtonSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchUserActionPerformed
        String name = jTextFieldUNameOrEmail.getText();
        
        if (name != null){
            //log..
            userModel.setUsersByNameOrEmail(name);
        } else {
            //log : something not specified
        }
    }//GEN-LAST:event_jButtonSearchUserActionPerformed

    private void jButtonEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUserActionPerformed
        int row = jTableUsers.getSelectedRow();
        if (row >= 0){
            
            
            setUserCombo();
        } else {
            //log not selected
        }
    }//GEN-LAST:event_jButtonEditUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LifeClickApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LifeClickApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LifeClickApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LifeClickApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        
        
        /* Create and display the form */
        //spusti aplikaci ve vlakne message dispatcheru
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LifeClickApp().setVisible(true);
            }
        });
    }
    //tabulce by melo byt jedno, odkud bere data; takze logika napojeni gui na db aplikaci by mela byt resena tady a tabulkam jenom predavany data
    
    private void setupInMemDataSource(){
        this.dataSource.setDatabaseName("memory:lifeclick");
        this.dataSource.setCreateDatabase("create");
        
        try (Connection connection = dataSource.getConnection()) {
            connection.prepareStatement(
                    "CREATE TABLE Users ("
                    + "id bigint primary key generated always as identity,"
                    + "email varchar(200) unique not null,"
                    + "password varchar(150),"
                    + "firstName varchar(100) not null,"
                    + "lastName varchar(100) not null,"
                    + "date timestamp not null default current_timestamp,"
                    + "image varchar(100))"
                    ).executeUpdate();
            
            connection.prepareStatement(
                    "CREATE TABLE Request ("
                    + "id bigint primary key generated always as identity,"
                    + "latitude double not null,"
                    + "longitude double not null,"
                    + "user_id bigint references Users (id) not null,"
                    + "date timestamp not null default current_timestamp)"
                    ).executeUpdate();
            
            connection.prepareStatement(
                    "CREATE TABLE REQUESTUSER ("
                    + "request_id bigint,"
                    + "user_id bigint)"
                    ).executeUpdate();
            
        } catch (SQLException ex) {
            //java.util.logging.Logger.getLogger(StartListener.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddRequest;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonAllRequests;
    private javax.swing.JButton jButtonAllRescuers;
    private javax.swing.JButton jButtonAllUsers;
    private javax.swing.JButton jButtonAuthorOfRequest;
    private javax.swing.JButton jButtonDeleteRequest;
    private javax.swing.JButton jButtonDeleteUser;
    private javax.swing.JButton jButtonEditUser;
    private javax.swing.JButton jButtonNewestRequest;
    private javax.swing.JButton jButtonRequestsOfUser;
    private javax.swing.JButton jButtonSearchUser;
    private javax.swing.JComboBox<UserComboItem> jComboBoxUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableRequests;
    private javax.swing.JTable jTableUsers;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldUEmail;
    private javax.swing.JTextField jTextFieldUName;
    private javax.swing.JTextField jTextFieldUNameOrEmail;
    private javax.swing.JTextField jTextFieldUSurname;
    private javax.swing.JTextField jTextFieldlongitude;
    // End of variables declaration//GEN-END:variables
}
